### ISSUE TITLE
Ruby client should check http response code before attempting to parse body

### ISSUE THREAD

**Issue by joshrose** [blueapron/kafka_rest-ruby#3]
Looking at errors like https://rollbar.com/blueapron/shipment-tracking-service/items/30/occurrences/22325447120/ , it seems like the error manifests as a JSON parsing error because the response body is in fact HTML with human-readable text about the service being unavailable. The REST client should check for a non-200 response code and report that as the error rather than report a JSON parsing error.

**Comment by nikhilofthesouth** [comment]
Good point. Will toss this on my radar to get fixed up sometime sometime over the next week.
