### ISSUE TITLE
Client library is using HTTP 1.0 for GET /topics requests

### ISSUE THREAD

**Issue by joshrose** [blueapron/kafka_rest-ruby#4]
Note that the POST requests, e.g. for posting new messages to a topic, use HTTP 1.1, but the GET /topics requests use 1.0, which is somewhat less efficient (particularly WRT persistent connections). Not sure if this is in our code or in the confluent code.

**Comment by nikhilofthesouth** [comment]
Assuming you saw that in the Papertrail logs. Those are the Marathon LB health checks initiating those calls, not the Kafka REST client.
